services:
  db:
    image: postgres:16.4-alpine3.19
    container_name: farcana-db
    volumes:
      - postgres_db:/data/db
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - '5432:5432'
    restart: always
    env_file:
      - .env.local

volumes:
  postgres_db:
